-- ============================================================
-- Classement Methodo : seed depuis Classement_algorithmes_BOAS.xlsx
-- (genere automatiquement — tier + justification pour les 48 outils)
-- A executer APRES add_methodo.sql (qui cree les colonnes).
-- ============================================================

update public.tools set tier_methodo = 'S', methodo_justification = 'Fiche complète : objectifs précis, méthodo documentée (doc ETL dédiée), cohorte décrite (570k patients), validation certifiée OHDSI/EHDEN, maintenance, installation pas-à-pas DBT, crédits, licence.' where id = 1;
update public.tools set tier_methodo = 'S', methodo_justification = 'Exceptionnel : périmètre, hypothèses/partis pris, limites, critères C1–C5 explicites, TOUS les codes CIM-10 et ATC listés, tables SNDS, validation vs cohorte Constances chiffrée, doc technique SAS+Python (structure, config, fonctions).' where id = 2;
update public.tools set tier_methodo = 'S', methodo_justification = 'Très détaillé : méthodo expliquée (best effort, OCR, distance de Levenshtein), validation quantifiée (précision/recall/F1 + tableaux de résultats), install PyPI, modules décrits, doc externe, contributions.' where id = 7;
update public.tools set tier_methodo = 'S', methodo_justification = 'Méthodo exemplaire : source de données, suivi, ~200 prédicteurs, split train/test détaillé, modèles ML comparés, formule du modèle, tableau complet de performances (F1/AUC/sensibilité/spécificité), limites, usage précis.' where id = 23;
update public.tools set tier_methodo = 'S', methodo_justification = 'Objectifs structurés, méthodo claire (Damerau-Levenshtein, blocking, 4 étapes), validation chiffrée multi-CHU (87,6 % de match, 99,17 % de qualité), publication JMIR, install/usage précis.' where id = 34;
update public.tools set tier_methodo = 'S', methodo_justification = 'Fiche exceptionnelle : deux études (EVIDEMS/DIONISOS), validation intra-base + externe vs gold standard OFSEP avec VPP/VPN et IC, publication DOI, critères en tableaux, usage ultra-détaillé (3 tables, macro %RLPSEPSNDS, règles temporelles).' where id = 37;
update public.tools set tier_methodo = 'S', methodo_justification = 'Méthodo complète (identification I63, reconstitution des séjours, modèles concurrents, conversion NIHSS via registre de Brest), validation interne + externe (registre de Dijon) avec tableaux stat et tests d''équivalence, scripts décrits.' where id = 38;
update public.tools set tier_methodo = 'A', methodo_justification = 'Bien documenté : fonctionnement décrit, résultats, install, usage avec exemples config.yaml complets, validation (synthétique + prod), maintenance. Méthodo simple mais tout est explicite.' where id = 8;
update public.tools set tier_methodo = 'A', methodo_justification = 'Usage extrêmement détaillé (chaque macro %xtr_* décrite avec options et exemple d''appel, référentiel en 6 étapes précises). Section méthodologie plus succincte (renvoi bonnes pratiques CNAM).' where id = 9;
update public.tools set tier_methodo = 'A', methodo_justification = 'Très précis : population, périodes, tous les actes CCAM listés avec libellés, critères d''exclusion justifiés, tables SNDS, scripts décrits un par un. Non validé (pas de source externe).' where id = 15;
update public.tools set tier_methodo = 'A', methodo_justification = 'Méthodo DREES détaillée par période (GHM 14Z08Z, actes JNJD002/JNJP001, DP O04), limites explicites, anonymisation, indicateurs listés, tables. Non validé.' where id = 16;
update public.tools set tier_methodo = 'A', methodo_justification = 'Méthodo riche : contexte médical (stades MRC, tableau), 3 étapes détaillées, critères de délivrance, listes CNAM référencées, limites médicales discutées franchement. Pas de validation externe.' where id = 17;
update public.tools set tier_methodo = 'A', methodo_justification = 'Méthodo de référence (article Med Care, doc ameli.fr, relecture critique par cliniciens), données détaillées. Renvoi important vers doc externe ; sections install/usage incohérentes (copiées d''un autre projet).' where id = 18;
update public.tools set tier_methodo = 'A', methodo_justification = 'Méthodo ML claire (modèles comparés, AUROC 0,85/0,83), validation avec tableaux de performance, usage reproductible pas-à-pas (scripts), article JACC, description du dataset.' where id = 19;
update public.tools set tier_methodo = 'A', methodo_justification = 'Fiche technique très complète : fonctionnement du DAG étape par étape, structure des fichiers, install pas-à-pas, usage détaillé, validation sur données open source. Méthodo technique plus que scientifique.' where id = 24;
update public.tools set tier_methodo = 'A', methodo_justification = 'Méthodo en 8 étapes détaillées (tables, code ATC J07CA02, spécialités, indicateurs Top_VAC), tables listées. Non validé, installation sommaire.' where id = 25;
update public.tools set tier_methodo = 'A', methodo_justification = 'Définitions précises des 5 populations (codes ALD, variables IMB_*), filtres PRS_NAT_REF listés, limites d''interprétation, programmes décrits. Non validé.' where id = 26;
update public.tools set tier_methodo = 'A', methodo_justification = 'Méthodo technique très fournie (PySpark, Parquet, graphe de jointures, défis), tables SNDS listées, critères qualité (complétude/unicité/conformité…), limites, install/usage détaillés. Validation interne seulement.' where id = 30;
update public.tools set tier_methodo = 'A', methodo_justification = 'Méthodo substantielle (définition RAC, champ, sources DCIR/PMSI, structure de la base, exclusions), validations internes + externes, publications de référence. Usage peu détaillé sur la fiche.' where id = 32;
update public.tools set tier_methodo = 'A', methodo_justification = 'Méthodo précise (31 comorbidités listées, 3 scores expliqués, fenêtre paramétrable), variables nécessaires, install/usage clairs. Validation interne, codes CIM-10 non détaillés sur la fiche.' where id = 35;
update public.tools set tier_methodo = 'A', methodo_justification = 'Méthodo argumentée (choix vs alternatives, modèle bayésien relationnel, limites explicites), validation décrite (publication IAS 2021, cas AVC vs étude DREES), sources de données publiques, DOI.' where id = 36;
update public.tools set tier_methodo = 'A', methodo_justification = 'Méthodo ML expliquée (Lasso feature selection, XGBoost) + doc PDF détaillée, tableaux de performances (précision/rappel/F1), limites de généralisation honnêtes, install pas-à-pas.' where id = 39;
update public.tools set tier_methodo = 'B', methodo_justification = 'Méthodo précise (codes départements, liste ATC complète, identifiants, indicateurs produits, tables DCIR). Pas de validation, pas de doc technique approfondie, usage sommaire.' where id = 3;
update public.tools set tier_methodo = 'B', methodo_justification = 'Méthodo détaillée (identifiants BEN_NIR_PSA/ANO, définition ayant-droit, régime, tables). Non validé, usage sommaire.' where id = 4;
update public.tools set tier_methodo = 'B', methodo_justification = 'Critères de ciblage clairs (ALD + MCO 5 ans + SSR, codes K50/K51), indicateurs listés, tables en images. Pas de validation, usage sommaire.' where id = 6;
update public.tools set tier_methodo = 'B', methodo_justification = 'Objectif clair (modèle hybride règles+DL), mais méthodo = renvoi à un article arXiv, install/usage = « voir la documentation ». Peu de détails sur la fiche elle-même.' where id = 20;
update public.tools set tier_methodo = 'B', methodo_justification = 'Objectif bien décrit (composants du framework), mais méthodo = renvoi article SSRN, usage = renvoi doc externe.' where id = 21;
update public.tools set tier_methodo = 'B', methodo_justification = 'Fonctionnalités listées, mais méthodo = renvoi doc externe, validation « dépend des algorithmes ».' where id = 22;
update public.tools set tier_methodo = 'B', methodo_justification = 'Fonctionnement géométrique bien décrit (étapes, limites, prérequis, usage pas-à-pas, workflow SIG en annexe), mais section Méthodologie = 1 mot (« Sommeil »). Non validé.' where id = 28;
update public.tools set tier_methodo = 'B', methodo_justification = 'Fonctionnalités et process de développement bien décrits (tests unitaires, revue de code, gouvernance), install et usage documentés. « Méthodologie » = process projet plus que méthode scientifique.' where id = 31;
update public.tools set tier_methodo = 'B', methodo_justification = 'Méthodo = choix d''architecture (RDF/DCAT/SHACL, FastAPI…), install Helm détaillée. Mais validation = 1 mot, peu sur le fonctionnement algorithmique.' where id = 33;
update public.tools set tier_methodo = 'B', methodo_justification = 'Méthodo brève sur la fiche (catégories avérée/potentielle, renvoi rapport IRDES 592), données décrites, install/usage très détaillés (12 programmes, nomenclatures). Validation vs enquête VQS via rapport externe.' where id = 40;
update public.tools set tier_methodo = 'B', methodo_justification = 'Idem PIC : méthodo brève (renvoi rapport IRDES 587), install/usage très détaillés (14 programmes + nomenclatures CCAM/CIM), données décrites. Validation en cours.' where id = 41;
update public.tools set tier_methodo = 'B', methodo_justification = 'Objectif + méthodo de collecte de données très détaillée (désarchivage, annotation, splits), publications. Mais méthodo/validation/usage des algorithmes eux-mêmes = renvoi aux dépôts GitHub.' where id = 42;
update public.tools set tier_methodo = 'B', methodo_justification = 'Méthodo décrite (parcours PMSI/DCIR/CépiDc, fichier var_def, format ndjson), validation chiffrée (95,3 % de mammographies retrouvées), usage concret mais concis.' where id = 44;
update public.tools set tier_methodo = 'C', methodo_justification = 'Fiche courte : méthodo = 3 phrases (identifiants), pas de description d''étapes, validation informelle, usage minimal.' where id = 10;
update public.tools set tier_methodo = 'C', methodo_justification = 'Méthodo courte mais pertinente (sélection par CIM-10 + motif, date de point expliquée), usage décrit (macro variables, sortie), validation informelle.' where id = 11;
update public.tools set tier_methodo = 'C', methodo_justification = 'Méthodo = 3 phrases (filtres CNAM, NIR_ANO_17), usage correct (modes DP/DR/DAS, paramètres), validation informelle.' where id = 12;
update public.tools set tier_methodo = 'C', methodo_justification = 'Méthodo brève mais précise (filtres CNAM, boucle mois de flux, régularisations, tableau de variables), usage minimal.' where id = 13;
update public.tools set tier_methodo = 'C', methodo_justification = 'Méthodo = 1 paragraphe généraliste (harmonisation formats/échelle communale), pas de critères précis ni d''algorithme décrit. Sources de données bien listées. Non validé.' where id = 14;
update public.tools set tier_methodo = 'C', methodo_justification = 'Objectif et données/variables cliniques bien décrits, mais toutes les sections techniques (méthodo, validation, install, usage) = renvoi GitHub.' where id = 43;
update public.tools set tier_methodo = 'C', methodo_justification = 'Objectif + critères d''évaluation du challenge (80/20), données décrites, mais méthodo/validation/install/usage = renvoi GitHub.' where id = 45;
update public.tools set tier_methodo = 'C', methodo_justification = 'Objectif et données bien décrits (4271 patients, IgE, collecte), publication en cours, mais sections techniques = renvoi GitHub.' where id = 46;
update public.tools set tier_methodo = 'C', methodo_justification = 'Objectif + tâche (zones pathologiques) et données (2500 couples de lames, annotation d''experts) décrits, reste = renvoi GitHub.' where id = 47;
update public.tools set tier_methodo = 'C', methodo_justification = 'Contexte médical et données très détaillés (75 000 images, 23 centres, 23 classes), mais méthodo/validation/install/usage = renvoi GitHub. Non validé.' where id = 48;
update public.tools set tier_methodo = 'D', methodo_justification = 'Fiche très maigre : méthodo = 1 phrase, pas de description du fonctionnement, validation contradictoire (« Validé » / « Non validé sur données externes »), renvoi à un tutoriel Google Drive externe.' where id = 5;
update public.tools set tier_methodo = 'D', methodo_justification = 'Objectif = 1 paragraphe correct, mais Méthodologie = 5 mots (« santé environnementale – exposition au bruit »), pas de validation, usage minimal (6 lignes génériques).' where id = 29;
update public.tools set tier_methodo = 'F', methodo_justification = 'La plus pauvre : AUCUNE section méthodologie, objectif en 1 phrase, aucun critère ni liste de médicaments sur la fiche, non validé, non maintenu (« liste à revoir »).' where id = 27;
